import type React from "react";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/header/page";
import Footer from "./components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>
        {/* Navbar positioned absolutely to overlay content */}
        <div className="">
          <Navbar />
        </div>

        {/* Add padding-top to prevent content from being hidden behind navbar */}
        <div className="">{children}</div>

        <div className="">
          <Footer />
        </div>
      </body>
    </html>
  );
}
